version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: easy-url-app
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:qa-${IMAGE_TAG}
    # image: jimloza/easy-link-app
    ports:
      - ${APP_PORT}:${APP_PORT}

    # env_file:
    #   - .env.local
